### ISSUE TITLE
APETH

### ISSUE THREAD

**Issue by sponnet** [AvadoDServer/ap-contracts#2]
# Phase 1 : Mint APETH

- [ ] receive ETH
- [ ] send ETH to seperate pool contract (TBD)
- [ ] mint APETH back to user
- [ ] mint 1% of excess APETH during this transaction & send to treasury account

# Phase 2 : Burn APETH

TBD
